name: formatting

on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "app/yarn.lock"
      - run: yarn install
      - run: yarn lint
      - run: yarn prettier:check
